# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-05 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
