# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='datetime',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end_time'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_id',
            field=models.CharField(max_length=10, verbose_name='user id'),
        ),
    ]
