# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-05 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_auto_20200605_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_time')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end_time')),
            ],
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_period',
            field=models.ManyToManyField(blank=True, to='backend_api.ActivityPeriod'),
        ),
    ]
