# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-05 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_auto_20200605_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='request_url',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='response_code',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_tz',
            field=models.CharField(default=datetime.datetime(2020, 6, 5, 7, 46, 59, 555447, tzinfo=utc), max_length=256, verbose_name='user tz'),
            preserve_default=False,
        ),
    ]
